---
title: "Live Session 1": 
author: "Jeremy Mikecz"
format: revealjs
editor: visual
---

## Prep

1.  [ ] finish setting up activity:
    1.  [ ] images
    2.  [ ] Github page with instructions
2.  [x] for 1.2.1 review teaching philosophy
3.  [ ] for 7.1 review Final Project documentation
4.  [ ] for 7.2 review AI policy

# 1. Course Welcome & Introduction

1.  [ ] Introduction
    1.  [ ] this course - Data Viz - why?
        1.  [x] opening video: Data Viz more than charts & graphs:
            1.  [x] tell stories
            2.  [x] make arguments
            3.  [x] prove or disprove hypotheses
            4.  [x] uncover insights
            5.  [x] communicate complex ideas
        2.  [x] key values: pattern recognition (including anomalies), communication
        3.  [x] don't save for the end to communicate what you already know; nor should you only create a few histograms and box plots at the beginning and then set them aside
    2.  [x] goal: create a group of information designers and literate and critical data viz consumers /
    3.  [x] me: - as alluded to in opening video: teacher –\> historian –\> digital historian –\> census project –\> Data Science job
        1.  [x] am not an expert on statistics or medical science; but you will get plenty of that throughout the rest of the program;
    4.  [ ] TA - Leah
2.  [ ] Expectations
    1.  [ ] community / tone
        1.  [x] collaborative learning community
            1.  [x] inclusive of people with diverse backgrounds (career backgrounds, skillsets, approaches)
            2.  [x] welcome experimentation, the revision of work, the evolution of ideas, the expression of diverse perspectives, and the pursuit of innovative approaches.
        2.  [x] development model of education - not blank slates; instead we learn by making connections to prior knowledge and experiences (thus the learning experience for each person should be unique)
        3.  [x] experiential education - hands-on activities + completion of real-world-applicable project
            1.  [x] scaffolded assignment - Final Project
    2.  [ ] weekly schedule
        1.  [x] Weekly overviews - structure of most weeks
        2.  [x] what to have ready for live sessions: CANVAS, repository, github page,
    3.  [ ] final project (discuss at end) and AI
    4.  [ ] collaborative support teams...

# 2. Assign Collaborative Support Groups

1.  [ ] Purpose of Teams
2.  [ ] Show where (CANVAS / Pages)

# 3. How Plots Lie Group Activity

## Group Member Introductions

## Activity

# 4. Discuss Activity

1.  Rules of transparent, legible, honest data viz (or truthful, functional, beautiful, insightful, enlightening)
2.  ITA shares Nathan Yau site - some rules

# 5. Discuss Lecture / Readings

1.  \[general Q abt Cairo?\]
    1.  defining data viz
    2.  additional criteria (reading discussion Q)
2.  How has your view of data visualization changed already after reading Alberto Cairo's book and viewing my videos?
3.  Lingering Questions / concerns

# 6. Demo of R Studio projects

1.  open Github, download button vs. clone
2.  show folder on my computer
3.  open R Studio
    1.  briefly demo how to create a project
    2.  how I can move back and forth between projects
    3.  mention renv??

# 7. Discussion of Syllabus / Final Projects

1.  [ ] AI policies - critical and exploratory approach to AI (opening video)

    1.  [ ] share weather data viz
    2.  [ ] my template?

2.  [ ] final project

    1.  [ ] go over assignment for this week

# Closing

3.  How Plots Lie Group Activity

    a.  Group Member Introductions

    b.  Activity

4.  Discuss: Group Activity + Readings

5.  Demo of R Studio projects (if time allows)

6.  Discussion of Syllabus / Final Project & Assignments
